dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9

env:
  global:
    - DO_BUILD=yes
    - DO_TEST=yes
    - CUDA_HOST=${HOME}/cuda
    - C_COMPILER=g++-4.9
    - CXX_COMPILER=gcc-4.9
matrix:
  include:
  - env:
    - CUDA_VERSION=92
  - env:
    - CUDA_VERSION=91
  - env:
    - CUDA_VERSION=90
  - env:
    - CUDA_VERSION=80

before_install:
- CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz"
- curl -o ${HOME}/cmake-tarball.tar.gz ${CMAKE_URL} &&
  mkdir -p ${HOME}/cmake &&
  tar xf ${HOME}/cmake-tarball.tar.gz -C ${HOME}/cmake --strip-components=1 &&
  export PATH=${HOME}/cmake/bin:${PATH}
- export PATH=${CUDA_HOST}/bin:${PATH}
- echo $PATH
- which cmake
- cmake --version
install:
  - ./ci/install_cuda_${CUDA_VERSION}.sh
script:
  - ./ci/build.sh